name: Update Kaggle Dataset

on:
  schedule:
    - cron: "0 0 1 * *"  # Runs monthly (first day at midnight UTC)
  workflow_dispatch:  # Manual trigger

jobs:
  update-dataset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Kaggle CLI
      run: pip install kaggle

    - name: Configure Kaggle API Key
      run: |
        mkdir -p ~/.kaggle
        echo '${{ secrets.KAGGLE_API_KEY }}' > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    - name: Download All CSV Files
      run: |
        mkdir -p data
        kaggle datasets download -d davidcariboo/player-scores -p data --unzip
        ls -lh data
